# Basic
title: Apple_QAQ
subtitle: ~这是我的个人博客nya~
welcome_message: <a href="https://www.bilibili.com/video/BV1GJ411x7h7?share_source=copy_web" target="_blank">- WELCOME -</a>
description: nya~喜欢水群的apple哟~
creator: <a href="https://github.com/apple-qaq">@Apple_QAQ</a>

url: "https://github.com/apple-qaq"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 参观我的博客

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: 查看我的项目, url: 'https://github.com/Apple-QAQ?tab=repositories'}
    - {title: Friend, description: 查看我的友链, url: 'https://apple-qaq.github.io/friendly'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: Apple-QAQ
    twitter: U_Apple_QAQ_U
    mail: apple_qaq@outlook.com

# Google Analytics
# ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-slate
