# Basic
title: Apple_qaq
subtitle: 这是我（Apple_QAQ）的个人博客nya～
welcome_message: <a href="https://space.bilibili.com/29474990" target="_blank">我的哔哩哔哩帐号</a>
description: nya～喜欢水群的apple～
creator: <a href="https://github.com/apple-qaq">@onevcat</a>

url: "https://github.com/apple-qaq"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: b;ue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 参观我的博客

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: 我的项目, url: 'https://github.com/Apple-QAQ?tab=repositories'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: Apple-QAQ
    twitter: U_Apple_QAQ_U
    bilibili: Apple_QAQ
    mail: apple_qaq@outlook.com

# Google Analytics
# ga:
    # id: your_ga_id
    # host: your_host
