# Basic
title: Apple_QAQの小站
subtitle: 喵呜~
welcome_message: <a href="https://vdse.bdstatic.com//192d9a98d782d9c74c96f09db9378d93.mp4" target="_blank">- WELCOME -</a>
description: <p>你好啊~你可以叫我猫猫~</p><p>本喵在读初二！喜欢音游和 archlinux！</p>
creator: <a href="https://github.com/apple-qaq">@Apple_QAQ</a>

url: "https://github.com/apple-qaq"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 参观我的博客

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: 查看我的项目, url: 'https://github.com/Apple-QAQ?tab=repositories'}
    - {title: Friend, description: 查看我的友链, url: 'https://apple-qaq.github.io/friendly'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: Apple-QAQ
    twitter: U_Apple_QAQ_U
    mail: apple_qaq@outlook.com

# Google Analytics
# ga:
    # id: your_ga_id
    # host: your_host

